### ISSUE TITLE
Error: ng:areq Bad Argument

### ISSUE THREAD

**Issue by linkstops** [laplasianin/angular-jqueryQueryBuilder#1]
thnks for ur response before, well i'm trying to import my table rows into  ur filter object but this doesnt work for me, could u help me out to inject the template querybuilder with my owns filters and rebuild the queryBuiler with the querys i need

i used this function but it didnt work

   $scope.build = function(){
                if($scope.fields){
                    for(var i = 0; i<$scope.fields.length; i++){
                        if($scope.fields.value_type == 'number'){
                            $scope.builder.options.filters.id = $scope.fields[i].src
                            $scope.builder.options.filters.name = $scope.fields[i].name
                            $scope.builder.options.filters.type = $scope.fields[i].value_type
                        }
                    }
                }
            };

            $scope.builder = {
                options: {
                    filters: [{
                        id: 'name',
                        label: 'Name',
                        type: 'integer'
                    }]
                },
                builder: {}
            };

**Comment by laplasianin** [comment]
According to stacktrace it doesn't look like issue relates to queryBuilder template. Can you try to reproduce it with not minified version and send trace?

**Comment by linkstops** [comment]
oki thnx , that was an issue in my controller, i update my question ;)

**Comment by laplasianin** [comment]
the easiest way to rebuild it is hide-n-show like this:
`
<query-builder ng-if="builderVisible" options="options" builder="qb"></query-builder>
`
```js
reinitializeFilter = function() {
  scope.builderVisible = false
  $timeout(function() {
    return $scope.builderVisible = true;
  }, 50);  
}
```
id query builder does not work at all for you please send stack trace
