### ISSUE TITLE
how to use this  directive  

### ISSUE THREAD

**Issue by shaoXunLu** [laplasianin/angular-jqueryQueryBuilder#3]
I have bowered this  to my project.
but querybuilder directive doesn't work

**Comment by laplasianin** [comment]
can you provide any details?

**Comment by shaoXunLu** [comment]
after bower  this ,my project index.html should  input what?
!
like other plugin
.........
<script src="bower_components/pdfjs-dist/build/pdf.js"></script>
<script src="bower_components/pdfjs-dist/build/pdf.worker.js"></script>
<script src="bower_components/angular-pdf/dist/angular-pdf.js"></script>
.........

**Comment by laplasianin** [comment]
Check example:

https://github.com/laplasianin/angular-jqueryQueryBuilder/blob/master/docs/examples/usage/index.html

**Comment by shaoXunLu** [comment]
![image](https://cloud.githubusercontent.com/assets/16425074/23992873/822a60cc-0a79-11e7-8496-8f88d8eec45c.png)
![image](https://cloud.githubusercontent.com/assets/16425074/23992923/a91e748e-0a79-11e7-875f-f0a6c076f73f.png)
