### ISSUE TITLE
How to use this with angular-cli

### ISSUE THREAD

**Issue by Caroga** [laplasianin/angular-jqueryQueryBuilder#5]
Hi, 
I've tried importing this into my angular-cli project, but I don't know how to import the module. What would the correct way be?

I've installed it, now looking to import it.

**Comment by laplasianin** [comment]
@Caroga, you can import it like any other dependency:

```
// Declare app level module which depends on views, and components
angular.module('myApp.controllers', ['angular-jquery-querybuilder']).
```

**Comment by Caroga** [comment]
I just now notice it's a package for **AngularJS** (1.x) and not **Angular** (>2.x).
That's mostly the reason I couldn't get this to work ^^.
Maybe update the docs to express this more? Even though I misread it, I think there might be more people.

Thanks for responding though! :+1:

**Comment by laplasianin** [comment]
Good catch, thanks, I will update readme
